### ISSUE TITLE
Checkbox not working

### ISSUE THREAD

**Issue by vishwajit76** [codeshell/fpdm#27]
Please provide some examples with a checkbox.
checkbox check and uncheck not working.

**Comment by mhuch** [comment]
Hi, i looked into the function set_field_checkbox and see that the $value is not used.
So i think this is the reason because its not work.

**Comment by vishwajit76** [comment]
i think $value is used in if condidtion to set $state.
 

> public function set_field_checkbox($name, $value)
        {
            //------------------------------------
            $offset_shift=0;
            $verbose_set=($this->verbose&&($this->verbose_level>1));
            //Get the line(s) of the misc field values
            if (isset($this->value_entries["$name"])) {
                if (isset($this->value_entries["$name"]["infos"]["checkbox_state_line"])
                && isset($this->value_entries["$name"]["infos"]["checkbox_no"])
                && isset($this->value_entries["$name"]["infos"]["checkbox_yes"])) {
                    $field_checkbox_line=$this->value_entries["$name"]["infos"]["checkbox_state_line"];
                    if ($field_checkbox_line) {
                        if ($verbose_set) {
                            echo "<br>Change checkbox of the field $name at line $field_checkbox_line to value [$value]";
                        }
                        $state = $this->value_entries["$name"]["infos"]["checkbox_no"];
                        if ($value) {
                            $state = $this->value_entries["$name"]["infos"]["checkbox_yes"];
                        }
                        $CurLine =$this->pdf_entries[$field_checkbox_line];
                        $OldLen=strlen($CurLine);
                        $CurLine = '/AS /'.$state;
                        $NewLen=strlen($CurLine);
                        $Shift=$NewLen-$OldLen;
                        $this->shift=$this->shift+$Shift;
                        //Saves
                        $this->pdf_entries[$field_checkbox_line]=$CurLine;
                        return $Shift;
                    // $offset_shift=$this->_set_field_value($field_checkbox_line, $state);
                    } else {
                        if ($verbose_set) {
                            echo "<br>Change checkbox value aborted, parsed checkbox definition incomplete.";
                        }
                    }
                } else {
                    if ($verbose_set) {
                        echo "<br>Change checkbox value aborted, the field $name has no checkbox definition.";
                    }
                }
            } else {
                $this->Error("set_field_checkbox failed as the field $name does not exist");
            }
            return $offset_shift;
        }

what are the changes in this function?

**Comment by vishwajit76** [comment]
I found the solution - [https://github.com/theChaosCoder/fpdm](url)
it worked when a checkbox's id and tooltip have the same value.

thank man.
this library is very useful.

**Comment by oneapple300690** [comment]
Hi vishwajit! Could you please help? I tried to put same name for checkbox's id and tooltip but it did not work.

**Comment by vishwajit76** [comment]
use this ---> https://www.pdfescape.com
for PDF form
