### ISSUE TITLE
Question, can we extracted list of fields(names) of the template pdf

### ISSUE THREAD

**Issue by samigroup** [codeshell/fpdm#54]
Hello, thank you for your work. 
is there  away to get an extracted list of fields of the template pdf? 
lets assume its compatible and even ran through the "pdftk modele.pdf output modele2.pdf" already, too.

**Comment by briezler** [comment]
try to use `pdftk modele2.pdf dump_data_fields`

**Comment by samigroup** [comment]
Briezler, Thank you!
